Fix multidex
Kright/android-scala-support pull request #9
Opened 2017-03-04 19:40 UTC by Kright

2017-03-08 13:03 UTC, faqqe commented on examples/HelloScalaApp/hellolibrary/build.gradle
> +	addScalaLibrary true
have we not agreed that this doesn't make sense? what is the scenario when you dont want to add scala library? even if this scenario existed, library should be added by default and excluding it should be explicit

2017-03-08 13:22 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaSupport.groovy
> +		if (isLibrary) return
code style: usually single-line `if` is only used if it is an `if-else` expression
`val x = if (a) 0 else 1`
single-line `if`-statement is confusing

2017-03-08 13:23 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaSupport.groovy
> +				project.tasks.getByName("transformClassesWithDexFor$name").doFirst { transformTask ->
whats up with weird formatting? is it you or github displays incorrectly?

2017-03-08 13:25 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaSupport.groovy
> +	private configuration(name, dependency) {
im not sure what i see in this method, lets discuss

2017-03-08 13:27 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MainDexModifier.groovy
> +	private final static multiDexClasses = [
you could prepend the 'android/support/multiDex/' part by using `map`

2017-03-08 13:28 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MainDexModifier.groovy
> +		assert manifestFile.isFile()
why

2017-03-08 13:32 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MainDexOverwrite.groovy
> + */
`MainDexOverwrite` is a strange name, consider `MainDexRules` or `MainDexOptions`

2017-03-08 13:33 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MultidexExtension.groovy
> +	def enabled(boolean value) {
`enabled` is a name for a property, not a method
you mean `enable`?

2017-03-08 13:34 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MultidexExtension.groovy
> +	private MainDexOverwrite mainDexModifier = null
usually you want the class and the method named the same if theres no particular reason not to

2017-03-08 15:56 UTC, Kright commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/MultidexExtension.groovy
> +	def enabled(boolean value) {
when user writes:
```
multiDex.enabled true 
```
He actually calls this method

2017-03-12 13:44 UTC, faqqe commented on README.md
> +adnroidScala {
type (android)

2017-03-12 13:54 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaExtension.groovy
> +		class MainDexOverwriteRule {
plural

2017-03-12 14:00 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaSupport.groovy
> +	private setMainDexModification() {
not a setter

2017-03-12 14:00 UTC, faqqe commented on plugin/src/main/groovy/com/github/kright/androidscalasupport/AndroidScalaSupport.groovy
> +	private setScalaCompileTaskAdding() {
addScalaCompile

2017-03-12 14:11 UTC, faqqe requested changes
fix typos

2017-03-12 14:17 UTC, faqqe approved these changes

2017-03-12 15:08 UTC, merged